/**
 * Required-param derivation and the pre-run binding refusal (#122).
 *
 * The point of these is not that a missing binding is *detected* — it is that a
 * missing binding is **not counted**. `PAGE_ERROR` and `ASSERTION_FAILED` are
 * the outcomes the §9 aggregates read as evidence about churn, and a forgotten
 * binding used to produce exactly those, at exactly the same place in the run.
 * So the assertions that matter most are the ones about what the metrics
 * emitter did and did not receive.
 */

import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { ReplayRunner } from "../../src/runner/replay.js";
import { bundleToProgram } from "../../src/runner/program.js";
import {
  UnboundParamsError,
  missingParams,
  requiredParams,
  requiredParamsForAction,
  requiredParamsForAssertion,
} from "../../src/runner/params.js";
import { interpolate } from "../../src/runner/templates.js";
import type {
  Assertion,
  CompiledAction,
  CompiledProgram,
  CompiledStep,
} from "../../src/runner/types.js";
import type { CompiledTrajectoryBundle } from "../../src/compiler/types.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const LIVE_BUNDLE = path.join(
  ROOT,
  "artifacts/compiled/traj-gate-live-create-stat-dashboard-from-testdata-9.5.21.bundle.json",
);

function assertion(overrides: Partial<Assertion> = {}): Assertion {
  return {
    schema_version: "1.0.0",
    assertion_id: "assert-0",
    type: "element-visible",
    strength: "strong",
    target: { locator: { strategy: "testid", testid: "done" } },
    expected: { visible: true },
    timeout_ms: 1000,
    failure_classification: "assertion_failed",
    ...overrides,
  };
}

function program(steps: CompiledStep[]): CompiledProgram {
  return {
    schema_version: "1.0.0",
    program_id: "prog-test",
    site_key: "fixture@local",
    task_key: "t",
    testbed_version: "fixture-v1",
    steps,
  };
}

function step(action: CompiledAction, a: Assertion = assertion()): CompiledStep {
  return { step_index: 0, compiled_action: action, assertion: a };
}

describe("required-param derivation mirrors what actually gets interpolated", () => {
  it("takes url_template holes from a navigate", () => {
    expect(
      requiredParamsForAction({
        type: "navigate",
        url_template: "http://{host}:{port}/dashboard/new",
        locator_fallback_chain: [],
      }),
    ).toEqual(["host", "port"]);
  });

  it("takes key holes from a press", () => {
    expect(
      requiredParamsForAction({ type: "press", key: "{key}", locator_fallback_chain: [] }),
    ).toEqual(["key"]);
  });

  it("takes param_refs from fill and select — the value-carrying actions", () => {
    for (const type of ["fill", "select"] as const) {
      expect(
        requiredParamsForAction({
          type,
          param_refs: ["panel_title"],
          locator_fallback_chain: [],
        }),
      ).toEqual(["panel_title"]);
    }
  });

  it("does not require a wait's param_refs — a recorded wait_ms is the alternative", () => {
    // ADR-0008: an absent binding here means "fall back to networkidle", not
    // "misconfigured". Requiring it would refuse programs that run fine today.
    expect(
      requiredParamsForAction({
        type: "wait",
        param_refs: ["settle_ms"],
        wait_ms: 250,
        locator_fallback_chain: [],
      }),
    ).toEqual([]);
  });

  it("ignores a url_template on an action that would never interpolate it", () => {
    expect(
      requiredParamsForAction({
        type: "click",
        url_template: "http://{host}/x",
        locator_fallback_chain: [],
      }),
    ).toEqual([]);
  });

  it("prefers regex_template over template, exactly as the evaluator does", () => {
    // Load-bearing, not fussiness: the real gate bundle asserts on
    // .../d/{dashboard_uid}/{dashboard_slug} with a regex_template alongside.
    // Those two values are generated by the site and cannot be bound, so
    // requiring every hole would refuse the gate's own program.
    const both = assertion({
      type: "url-matches",
      target: { url_template: "http://{host}:{port}/d/{dashboard_uid}/{slug}" },
      expected: {
        template: "http://{host}:{port}/d/{dashboard_uid}/{slug}",
        regex_template: "^http://[^/?#]+:[^/?#]+/d/[^/?#]+/[^/?#]+$",
      },
    });
    expect(requiredParamsForAssertion(both)).toEqual([]);

    const templateOnly = assertion({
      type: "url-matches",
      target: { url_template: "http://{host}:{port}/dashboards" },
      expected: {},
    });
    expect(requiredParamsForAssertion(templateOnly)).toEqual(["host", "port"]);
  });

  it("requires nothing from an assertion type that interpolates nothing", () => {
    expect(requiredParamsForAssertion(assertion())).toEqual([]);
    expect(
      requiredParamsForAssertion(
        assertion({ type: "count-equals", expected: { count: 3 } }),
      ),
    ).toEqual([]);
  });

  it("unions across steps and sorts", () => {
    const p = program([
      step({
        type: "navigate",
        url_template: "http://{host}:{port}/",
        locator_fallback_chain: [],
      }),
      {
        step_index: 1,
        compiled_action: { type: "fill", param_refs: ["alias"], locator_fallback_chain: [] },
        assertion: assertion({
          type: "text-matches",
          expected: { template: "Saved {alias}" },
        }),
      },
    ]);
    expect(requiredParams(p)).toEqual(["alias", "host", "port"]);
  });

  it("unions a declared required_params rather than trusting it", () => {
    // A declaration can add a requirement but never quietly remove one: the two
    // can only disagree by drift, and under-refusing is the failure being fixed.
    const p: CompiledProgram = {
      ...program([
        step({
          type: "navigate",
          url_template: "http://{host}/",
          locator_fallback_chain: [],
        }),
      ]),
      required_params: ["declared_only"],
    };
    expect(requiredParams(p)).toEqual(["declared_only", "host"]);
  });
});

describe("bundleToProgram declares what the program needs", () => {
  it("writes required_params, and it matches what the steps derive", async () => {
    const bundle = JSON.parse(
      await readFile(LIVE_BUNDLE, "utf8"),
    ) as CompiledTrajectoryBundle;
    const p = bundleToProgram(bundle, "9.5.21");

    // The real bundle, checked against the real bundle: host/port from step 0's
    // navigate, plus the four fills. dashboard_uid and dashboard_slug are NOT
    // here — they are site-generated and their assertions carry a regex.
    expect(p.required_params).toEqual([
      "dashboard_title",
      "host",
      "panel_title",
      "port",
      "series_alias",
      "series_count",
    ]);
    expect(requiredParams(p)).toEqual(p.required_params);
  });
});

describe("run() refuses before step 0", () => {
  const navigateProgram = program([
    step({
      type: "navigate",
      url_template: "http://{host}:{port}/dashboard/new",
      locator_fallback_chain: [],
    }),
  ]);

  it("names every missing param, not just the first", async () => {
    const runner = new ReplayRunner({ dryRun: true });
    await expect(runner.run(navigateProgram, {})).rejects.toThrow(UnboundParamsError);
    await expect(runner.run(navigateProgram, {})).rejects.toThrow(/host, port/);
  });

  it("emits no metrics at all — a refused run is absent, not failed", async () => {
    // The assertion the whole issue is about. A row here would land in the §9
    // denominators as evidence about churn.
    const runner = new ReplayRunner({ dryRun: true });
    await expect(runner.run(navigateProgram, { host: "127.0.0.1" })).rejects.toThrow();
    expect(runner.getMetricsEmitter().getRows()).toEqual([]);
  });

  it("says the run was not attempted, so it cannot be read as a failure", async () => {
    const runner = new ReplayRunner({ dryRun: true });
    await expect(runner.run(navigateProgram, {})).rejects.toThrow(/not.*a failure/i);
  });

  it("carries the missing names as data, not only in the message", async () => {
    const runner = new ReplayRunner({ dryRun: true });
    const err = await runner.run(navigateProgram, { port: 3000 }).catch((e: unknown) => e);
    expect(err).toBeInstanceOf(UnboundParamsError);
    expect((err as UnboundParamsError).missing).toEqual(["host"]);
    expect((err as UnboundParamsError).code).toBe("UNBOUND_PARAMS");
    expect((err as UnboundParamsError).programId).toBe("prog-test");
  });

  it("runs normally once everything is bound", async () => {
    const runner = new ReplayRunner({ dryRun: true, dryRunOutcomes: ["PASS"] });
    const result = await runner.run(navigateProgram, { host: "127.0.0.1", port: 3000 });
    expect(result.task_success).toBe(true);
    expect(runner.getMetricsEmitter().getRows()).toHaveLength(2); // one step, one run
  });

  it("is unaffected by a program that needs nothing", async () => {
    const runner = new ReplayRunner({ dryRun: true, dryRunOutcomes: ["PASS"] });
    const result = await runner.run(program([step({ type: "click", locator_fallback_chain: [] })]));
    expect(result.task_success).toBe(true);
  });

  // The silent one, called out in the issue: a hole in a URL *path* segment
  // interpolates to a valid URL and navigates to a real, wrong page. There is
  // no throw to catch and no error to classify — the run simply measures the
  // wrong thing. Verified against Node's WHATWG URL below.
  it("refuses a path-segment hole rather than navigating to the escaped literal", async () => {
    const escaped = new URL(interpolate("http://localhost:3000/d/{dash_uid}/view", {}));
    expect(escaped.pathname).toBe("/d/%7Bdash_uid%7D/view"); // a real request, wrong page

    const p = program([
      step({
        type: "navigate",
        url_template: "http://localhost:3000/d/{dash_uid}/view",
        locator_fallback_chain: [],
      }),
    ]);
    const runner = new ReplayRunner({ dryRun: true });
    await expect(runner.run(p, {})).rejects.toThrow(/dash_uid/);
    expect(runner.getMetricsEmitter().getRows()).toEqual([]);
  });
});

describe("missingParams / interpolate", () => {
  it("reports what is missing without running anything", () => {
    const p = program([
      step({
        type: "navigate",
        url_template: "http://{host}:{port}/",
        locator_fallback_chain: [],
      }),
    ]);
    expect(missingParams(p, { host: "h" })).toEqual(["port"]);
    expect(missingParams(p, { host: "h", port: 1 })).toEqual([]);
  });

  it("treats a falsy binding as bound — presence decides, not truthiness", () => {
    const p = program([
      step({ type: "fill", param_refs: ["count"], locator_fallback_chain: [] }),
    ]);
    expect(missingParams(p, { count: 0 })).toEqual([]);
    expect(missingParams(p, { count: "" })).toEqual([]);
  });

  it("leaves an unbound hole intact, deliberately", () => {
    // Still reachable, and only, through an action a *repair* proposed: the
    // model can return a corrected_action carrying a template the run-start
    // check never saw. interpolate stays total so that step fails and is
    // recorded, rather than aborting a run and losing what it already measured.
    expect(interpolate("http://{host}/x", {})).toBe("http://{host}/x");
    expect(interpolate("http://{host}/x", { host: "h" })).toBe("http://h/x");
  });
});
