/**
 * Required-parameter derivation and the pre-run binding check (#122).
 *
 * Nothing used to validate that a program's parameters were bound before it
 * ran, and there was nowhere to look up what it required. `interpolate` leaves
 * an unbound hole as literal text by design, and `run()` takes
 * `params: ParamBindings = {}` — an empty default.
 *
 * ## Why this is a measurement problem, not an ergonomics one
 *
 * The value-carrying actions already fail closed: `fill` and `select` return
 * `PAGE_ERROR` with "missing bound param value". The template paths had no
 * equivalent, and three of their four shapes report a **caller error as a
 * site-churn failure**:
 *
 * | Shape | Unbound `{hole}` |
 * | --- | --- |
 * | `http://{host}:{port}/dashboard/new` | `new URL()` throws → `PAGE_ERROR` |
 * | `http://localhost:3000/d/{uid}/view` | *valid URL* — a real request to `/d/%7Buid%7D/view` |
 * | `press` with a templated `key` | literal `{key}` throws → `PAGE_ERROR` |
 * | `url-matches` / `text-matches` | expected keeps the hole → `ASSERTION_FAILED` |
 *
 * `PAGE_ERROR` and `ASSERTION_FAILED` are the outcomes the gate exists to
 * count. A forgotten binding produces exactly those, at exactly the same place
 * in the run, and nothing in the metric row distinguishes it — so a matrix run
 * with one misconfigured parameter reports a *worse gate number* and looks like
 * ordinary churn. A refused run is therefore not a failed run; it is an absent
 * one, and it contributes to no §9 denominator.
 *
 * ## Required means "will actually be interpolated"
 *
 * The derivation below mirrors `executeAction` and `evaluateAssertion` branch
 * for branch, and that precision is load-bearing rather than fussiness. The one
 * real compiled bundle in the tree asserts on
 * `http://{host}:{port}/d/{dashboard_uid}/{dashboard_slug}?orgId=1` — but with
 * a `regex_template` alongside it, which is what the evaluator actually uses.
 * `dashboard_uid` and `dashboard_slug` are generated by the site and **cannot**
 * be bound by a caller. Requiring every hole in every template would refuse the
 * gate's own program.
 *
 * The risk this trades for is drift: if the evaluator's precedence changes and
 * this does not, a hole becomes required that is never used, or stops being
 * required when it is. `tests/unit/runner-params.test.ts` pins the pairs.
 */

import type {
  Assertion,
  CompiledAction,
  CompiledProgram,
  CompiledStep,
  ParamBindings,
} from "./types.js";
import { PARAM_HOLE } from "./templates.js";

/** Hole names in a template, in order of appearance, deduplicated. */
export function templateHoles(template: string | undefined): string[] {
  if (!template) return [];
  const names = new Set<string>();
  for (const match of template.matchAll(PARAM_HOLE)) names.add(match[1]!);
  return [...names];
}

/**
 * Params an action needs bound.
 *
 * Gated on `type` because that is what `executeAction` does: it interpolates
 * `url_template` only for `navigate` and `key` only for `press`. `param_refs`
 * counts for `fill` and `select` — the two actions that already refuse without
 * a value — but **not** for `wait`, where a runtime-bound duration is an
 * optional alternative to a recorded `wait_ms` (ADR-0008) and its absence means
 * "fall back to networkidle", not "misconfigured".
 */
export function requiredParamsForAction(action: CompiledAction): string[] {
  switch (action.type) {
    case "navigate":
      return templateHoles(action.url_template);
    case "press":
      return templateHoles(action.key);
    case "fill":
    case "select":
      return [...(action.param_refs ?? [])];
    default:
      return [];
  }
}

/**
 * Params an assertion needs bound.
 *
 * `regex_template` wins over `template` / `target.url_template` in both
 * templated assertion types, so only the branch that will actually run
 * contributes. Every other assertion type interpolates nothing.
 */
export function requiredParamsForAssertion(assertion: Assertion): string[] {
  switch (assertion.type) {
    case "text-matches":
      return templateHoles(
        assertion.expected?.regex_template ?? assertion.expected?.template,
      );
    case "url-matches":
      return templateHoles(
        assertion.expected?.regex_template ??
          assertion.target?.url_template ??
          assertion.expected?.template,
      );
    default:
      return [];
  }
}

export function requiredParamsForStep(step: CompiledStep): string[] {
  return [
    ...new Set([
      ...requiredParamsForAction(step.compiled_action),
      ...requiredParamsForAssertion(step.assertion),
    ]),
  ];
}

/**
 * Every param the program must have bound before it runs, sorted.
 *
 * The **union** of what the program declares (`required_params`, written by
 * `bundleToProgram` so a caller can ask without re-deriving) and what its steps
 * actually need. A union rather than a preference, because the two can only
 * disagree by drift — a hand-written or stale declaration — and a union means a
 * declaration can add a requirement but never quietly remove one.
 */
export function requiredParams(program: CompiledProgram): string[] {
  const names = new Set<string>(program.required_params ?? []);
  for (const step of program.steps) {
    for (const name of requiredParamsForStep(step)) names.add(name);
  }
  return [...names].sort();
}

/** Required params with no binding, sorted. Empty when the program can run. */
export function missingParams(
  program: CompiledProgram,
  params: ParamBindings,
): string[] {
  return requiredParams(program).filter(
    (name) => !Object.prototype.hasOwnProperty.call(params, name),
  );
}

/**
 * A run that did not happen because the caller did not bind what the program
 * declares.
 *
 * Thrown before step 0 and before any metric is emitted, so a binding error can
 * never be counted as a step failure — the whole point. It is deliberately an
 * exception rather than a `StepOutcome`: there is no outcome to report, because
 * nothing was attempted.
 */
export class UnboundParamsError extends Error {
  readonly code = "UNBOUND_PARAMS" as const;
  readonly missing: readonly string[];
  readonly programId: string;

  constructor(programId: string, missing: readonly string[]) {
    super(
      `program ${programId} cannot run: unbound parameter(s) ` +
        `${missing.join(", ")}. Bind them and re-run — this run was not ` +
        "attempted and is not a failure.",
    );
    this.name = "UnboundParamsError";
    this.programId = programId;
    this.missing = [...missing];
  }
}

/**
 * Throw unless every required param is bound.
 *
 * Exported so a caller can ask *before* paying for a container boot or a
 * browser launch — `experiments/gate-v1/run-matrix.ts` does exactly that. Names
 * only: a required-param **name** is declared, a value never is.
 */
export function assertParamsBound(
  program: CompiledProgram,
  params: ParamBindings,
): void {
  const missing = missingParams(program, params);
  if (missing.length > 0) {
    throw new UnboundParamsError(program.program_id, missing);
  }
}
